chore: refactor style of armbian start_chroot_script
Signed-off-by: Stephan Wendel <me@stephanwe.de>

diff --git a/src/modules/armbian/start_chroot_script b/src/modules/armbian/start_chroot_script
--- a/src/modules/armbian/start_chroot_script
+++ b/src/modules/armbian/start_chroot_script
@@ -1,12 +1,16 @@
 #!/usr/bin/env bash
-# MainsailOS Specific Tweaks for armbian images
-# written by Stephan Wendel aka KwadFan
-# <me@stephanwe.de>
-# GPL V3
-########
+#### MainsailOS Specific Tweaks for armbian images
+####
+#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
+#### Copyright 2023 - till today
+#### https://github.com/mainsail-crew/MainsailOS
+####
+#### This File is distributed under GPLv3
+####
 
+# shellcheck enable=require-variable-braces
 # Source error handling, leave this in place
-set -xe
+set -Ee
 
 # Source CustomPIOS common.sh
 # shellcheck disable=SC1091
@@ -24,15 +28,6 @@ is_board_type() {
     echo "${board}"
 }
 
-# Install armbian specific packages
-apt update
-# shellcheck disable=SC2086
-check_install_pkgs ${ARMBIAN_DEPS}
-
-# passwordless sudo during install
-# Will be removed in cleanup
-echo "${BASE_USER} ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
-
 # Base User groups
 # Shameless "stolen" from
 # https://github.com/guysoft/CustomPiOS/blob/devel/src/variants/armbian/pre_chroot_script
@@ -44,37 +39,59 @@ if_group_exists_run() {
     fi
 }
 
+# passwordless sudo during install
+# Will be removed in cleanup
+echo "${BASE_USER} ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
+
+
+## Step 1: Install armbian specific packages
+apt update
+# shellcheck disable=SC2086
+check_install_pkgs ${ARMBIAN_DEPS}
+
+
+
 # set groups
 if_group_exists_run i2c usermod -aG i2c "${BASE_USER}"
 usermod -aG video,audio,plugdev,games,netdev,sudo "${BASE_USER}"
 
-# Patch sshd_config
+## Step 2: Set default groups
 sed -i 's/PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
 sed -i 's/^X11Forwarding/#X11Forwarding/' /etc/ssh/sshd_config
 sed -i 's/^#MaxAuthTries 6/MaxAuthTries 3/' /etc/ssh/sshd_config
+## END
 
-# Try patching first login in build stage
+## Step 4: Try patching first login in build stage
 if [ -f "/root/.not_logged_in_yet" ]; then
     rm -f /root/.not_logged_in_yet
 fi
+## END
 
-# Move armbian-release to display mainsailos-release
-mv /etc/armbian-release /etc/armbian-release-info.txt
+## Step 5: Move armbian-release to display mainsailos-release
+if [[ -f "/etc/armbian-release" ]]; then
+    echo_green "Armbian release file found! moving to: 'armbian-release-info.txt'"
+    mv /etc/armbian-release /etc/armbian-release-info.txt
+else
+    echo_red "Armbian release file not found! [SKIPPED]"
+fi
+## END
 
-# update motd
+## Step 6: Patch dynamic motd
+echo_green "Patch dynamic motd ..."
 unpack /filesystem/root /
 chmod +x /etc/update-motd.d/*
 if [ -f "/etc/default/armbian-motd" ]; then
     sed -i 's/MOTD_DISABLE=""/MOTD_DISABLE="header"/' /etc/default/armbian-motd
 fi
+## END
 
-
+## Step 7: Enable SPI interface by default
 echo_green "Enable SPI interface on Orange Pi SBC's ..."
 
-# Step 1: Copy default config to backup file
+# Substep 1: Copy default config to backup file
 cp "${ARMBIAN_CONFIG_TXT_FILE}" "${ARMBIAN_CONFIG_BAK_FILE}"
 
-# Step 2: Enable SPI in armbianEnv.txt depending on device
+# Substep: Enable SPI in armbianEnv.txt depending on device
 
 ## OrangePi 3 LTS
 if [[ "$(is_board_type)" == "orangepi3-lts" ]]; then
@@ -87,7 +104,8 @@ if [[ "$(is_board_type)" == "orangepi4-lts" ]]; then
     echo "param_spidev_spi_bus=1" >> "${ARMBIAN_CONFIG_TXT_FILE}"
 fi
 
-# Step 3: add spi-dev module to /etc/modules
+# Substep 3: add spi-dev module to /etc/modules
 echo "spi-dev" >> "${ARMBIAN_MODULES_FILE}"
 
 echo_green "Enable SPI interface on Orange Pi SBC's ... DONE!"
+## END
