fix: activate wifi before reload config in headless_nm
Signed-off-by: Stefan Dej <meteyou@gmail.com>

diff --git a/modules/generic/files/headless-nm/headless_nm b/modules/generic/files/headless-nm/headless_nm
--- a/modules/generic/files/headless-nm/headless_nm
+++ b/modules/generic/files/headless-nm/headless_nm
@@ -108,6 +108,16 @@ set_regdomain() {
     esac
 }
 
+enable_wifi() {
+    log "Enabling WiFi functionality"
+
+    if ! nmcli radio wifi on; then
+        log "ERROR: Could not enable WiFi"
+        return 1
+    fi
+    return 0
+}
+
 # MAIN
 main() {
     if [[ ! -f "${SETUPFILE}" ]]; then
@@ -143,6 +153,8 @@ main() {
 
     # NetworkManager only accepts 0600 permissions for configs
     chmod 0600 "${CONNFILE}"
+
+    enable_wifi
 
     # Reload NetworkManager to apply changes, if it is active
     if systemctl is-active --quiet NetworkManager; then
