refactor(crowsnest): refactor module with section headers

diff --git a/modules/generic/53-crowsnest b/modules/generic/53-crowsnest
--- a/modules/generic/53-crowsnest
+++ b/modules/generic/53-crowsnest
@@ -1,15 +1,21 @@
 #!/bin/bash
-
-set -x
-set -e
-
+set -xe
 export LC_ALL=C
 
-# load common functions
+########################################
+# Functions and Basic Configuration    #
+########################################
+
+# Load common functions and set up cleanup trap
 source /common.sh
 install_cleanup_trap
 
+# Load additional configuration (e.g., BASE_USER)
 source /files/00-config
+
+########################################
+# Configuration                        #
+########################################
 
 REPO="https://github.com/mainsail-crew/crowsnest.git"
 DEPS=(git)
@@ -19,11 +25,23 @@ if [[ "$(is_raspbian)" = "1" ]]; then
     INSTALL_SCRIPT="/home/${BASE_USER}/crowsnest/tools/libs/pkglist-rpi.sh"
 fi
 
+########################################
+# Install System Packages              #
+########################################
+
 apt-get install --yes "${DEPS[@]}"
+
+########################################
+# Clone Repository                     #
+########################################
 
 pushd "/home/${BASE_USER}" &> /dev/null || exit 1
 sudo -u "${BASE_USER}" git clone ${REPO} crowsnest
 popd &> /dev/null || exit 1
+
+########################################
+# Installation Crowsnest Dependencies  #
+########################################
 
 PKGLIST=$(
     # shellcheck disable=SC1090
@@ -34,9 +52,17 @@ PKGLIST=$(
 read -ra PKGARRAY <<< "$PKGLIST"
 apt-get install --yes "${PKGARRAY[@]}"
 
+########################################
+# Installation Crowsnest               #
+########################################
+
 pushd "/home/${BASE_USER}/crowsnest" &> /dev/null || exit 1
 export CROWSNEST_UNATTENDED=1
 make install
 popd &> /dev/null || exit 1
+
+########################################
+# Enable Service                       #
+########################################
 
 systemctl_if_exists enable crowsnest.service
