refactor(unhold-packages): refactor module with section headers

diff --git a/modules/generic/99-unhold-packages b/modules/generic/99-unhold-packages
--- a/modules/generic/99-unhold-packages
+++ b/modules/generic/99-unhold-packages
@@ -1,15 +1,20 @@
 #!/bin/bash
-
-set -x
-set -e
-
+set -xe
 export LC_ALL=C
 
-# load common functions
+########################################
+# Functions and Basic Configuration    #
+########################################
+
+# Load common functions and set up cleanup trap
 source /common.sh
 install_cleanup_trap
 
+# Load additional configuration (e.g., BASE_USER)
 source /files/00-config
 
-# unhold linux kernel updates
+########################################
+# Unhold linux kernel updates          #
+########################################
+
 apt-mark unhold "${PKGS[@]}" > /dev/null 2>&1 || true
