Register timelapse moonraker extension

diff --git a/src/modules/timelapse/start_chroot_script b/src/modules/timelapse/start_chroot_script
--- a/src/modules/timelapse/start_chroot_script
+++ b/src/modules/timelapse/start_chroot_script
@@ -49,10 +49,30 @@ function add_timelapse_entry {
     fi
 }
 
+register_moonraker_extension() {
+    EXT_NAME=$1
+    EXT_PATH=$2
+    EXT_FILE=$3
+    echo_green "Registering moonraker extension '$EXT_NAME' with the RatOS Configurator..."
+    if [ ! -e $EXT_PATH/$EXT_FILE ]
+    then
+        echo "ERROR: The file you're trying to register does not exist"
+        exit 1
+    fi
+    curl --silent --fail -X POST 'http://localhost:3000/configure/api/trpc/moonraker-extensions.register' -H 'content-type: application/json' --data-raw "{\"json\":{\"extensionName\":\"$EXT_NAME\",\"path\":\"$EXT_PATH\",\"fileName\":\"$EXT_FILE\"}}" > /dev/null
+    if [ $? -eq 0 ]
+    then
+        echo "Registered $EXT_NAME successfully."
+    else
+        echo "ERROR: Failed to register $EXT_NAME. Is the RatOS configurator running?"
+        exit 1
+    fi
+}
+
 echo_green "Installing moonraker-timelapse plugin ..."
 
 ### Install template file
-unpack /filesystem/home/${BASE_USER} /home/${BASE_USER} ${BASE_USER}
+# unpack /filesystem/home/${BASE_USER} /home/${BASE_USER} ${BASE_USER}
 
 ## Install all deps at once for time consumption reasons.
 ## APT: Update Repo Database and install Dependencies
@@ -70,9 +90,7 @@ gitclone TIMELAPSE_REPO moonraker-timelapse
 
 ## Link component
 if [ -d "${TIMELAPSE_TARGET_DIR}" ]; then
-    echo "Linking extension to moonraker ..."
-    sudo -u "${BASE_USER}" \
-    ln -sf "${TIMELAPSE_SRC_DIR}/component/timelapse.py" "${TIMELAPSE_TARGET_DIR}/timelapse.py"
+    register_moonraker_extension "timelapse" "${TIMELAPSE_SRC_DIR}/component" "timelapse.py"
 fi
 
 ## Link timelapse.cfg
@@ -88,7 +106,6 @@ fi
 
 
 popd || exit 1
-
 
 ## Done message
 echo_green "Installing moonraker-timelapse plugin ... done!"
