check SHAKETUNE_INSTALL_SH is set or not

diff --git a/src/modules/shaketune/start_chroot_script b/src/modules/shaketune/start_chroot_script
--- a/src/modules/shaketune/start_chroot_script
+++ b/src/modules/shaketune/start_chroot_script
@@ -25,6 +25,15 @@ install_cleanup_trap
 
 ### Download and Install Shake&Tune
 echo_green "Installing Shake&Tune ..."
+
+# Check if SHAKETUNE_INSTALL_SH is set
+if [ -z "${SHAKETUNE_INSTALL_SH}" ]; then
+  echo "Error: SHAKETUNE_INSTALL_SH is not set or is empty."
+  exit 1
+fi
+
+echo "${SHAKETUNE_INSTALL_SH}"
+
 pushd /home/"${BASE_USER}" &> /dev/null || exit 1
 sudo -u "${BASE_USER}" wget -q --show-progress -O "${SHAKETUNE_INSTALL_SH}" | bash
 
